/* This program demonstrates the difference in assembly generated by GCC under
 * different coding models (small, medium and large). To get the most out of
 * this code, please read a bit into ELF and Dynamic Loading. My notes has good
 * references to resources that will help.
 *
 * Notes: https://www.sheharyaar.in/notes/sysv-elf-dso/
 * Disclaimer: This code was generated by Gemini 2.5 Pro for educational
 * purposes.
 * */

#include <stdio.h>

/* A small global variable, likely to be placed in a section that is close to
 * the code. */
int small_global_var = 42;

/* A very large global array. Its size and position in memory are what will
 * force the different code models to act differently. */
char large_global_array[3UL * 1024 * 1024 * 1024] = {1}; // 3GB array

int main() {
        // Access the small, nearby global variable.
        printf("Small global variable: %d\n", small_global_var);

        // Access the large, distant global array.
        // We access an element far into the array to see the addressing.
        printf("Large global array element: %d\n",
               large_global_array[2UL * 1024 * 1024 * 1024 - 1]);

        return 0;
}